language: rust
rust:
  - stable
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
cache: cargo
script:
  - cargo build --verbose
  - cargo test --verbose
  - wget https://download.geofabrik.de/europe/germany/bremen-latest.osm.pbf
  - target/release/osmtoroadgraph --verbose -n c bremen-latest.osm.pbf