language: rust
rust:
  - stable
  - nightly
  before_script:
    - rustup component add clippy
  matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
cache: cargo
script:
  # check clippy
  - cargo clippy -- -D warnings
  # test
  # - cargo test
  # check if conversion is successful
  # - cargo build --release
  # - wget https://download.geofabrik.de/europe/germany/bremen-latest.osm.pbf
  # - target/release/osmtoroadgraph --verbose -n c bremen-latest.osm.pbf